name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      
      # - name: Setup Node 18
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      #     cache: 'yarn'

      # - name: Install deps
      #   run: yarn

      # - name: Build app
      #   run: yarn build

      - name: Auth to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Deploy to Google Cloud App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.dev.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        # RyP(?.7Xf%PG@Ddk
        # Y*:gPX$%h;F=YyP_